MVCHomework1/MVCHomework1/Models/Database/PizzaDatabase.cs
using MVCHomework1.Models.Domain;

namespace MVCHomework1.Models.Database
{
    public static class PizzaDatabase
    {

        public static List<Pizza> LIST_PIZZA = new List<Pizza>
        {
            new Pizza(1,Enum.PizzaType.Capricciosa,12),
            new Pizza(2,Enum.PizzaType.Margherita,14),
            new Pizza (3,Enum.PizzaType.QuattroStagioni,10),
            new Pizza (4,Enum.PizzaType.Diavola,17),
            new Pizza (5,Enum.PizzaType.Marinara,14)
        };

        public static List<User> USERS = new List<User>
        {
            new User(1,"Tom","Holand","Mil 81 road","+222 344 122"),
            new User(2,"Kevin","Dor","Bevetly 21 road","+222 222 222"),
            new User(3,"Elizabeth","Brown","Ewnue 10 ul","+222 124 154"),
        };

        public static List<Order> ORDERS = new List<Order>
        {
            new Order(1,12,false,2,1),
            new Order(2,14,false,1,2),
            new Order(3,17,false,3,4),
        };
    }
}

MVCHomework1/MVCHomework1/Models/Domain/Order.cs
namespace MVCHomework1.Models.Domain
{
    public class Order
    {
        public int Id { get; set; }

        public decimal Price { get; set; }

        public bool IsDelivered { get; set; }

        public int UserId { get; set; }

        public int PizzaId { get; set; }

        public Order(int id, decimal price, bool isDelivered, int userId,int pizzaid)
        {
            Id = id;
            Price = price;
            IsDelivered = isDelivered;
            UserId = userId;
            PizzaId = pizzaid;
        }
    }
}

MVCHomework1/MVCHomework1/Models/Domain/Pizza.cs
using MVCHomework1.Models.Enum;

namespace MVCHomework1.Models.Domain
{
    public class Pizza
    {
        public int Id { get; set; }

        public PizzaType Name { get; set; }

        public decimal Price { get; set; }

        public Pizza(int id, PizzaType name, decimal price)
        {
            Id = id;
            Name = name;
            Price = price;
        }
    }
}

MVCHomework1/MVCHomework1/Models/Domain/User.cs
namespace MVCHomework1.Models.Domain
{
    public class User
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string LastName { get; set; }

        public string Adress { get; set; }

        public string Phone { get; set; }

        public User(int id, string name, string lastName, string adress, string phone)
        {
            Id = id;
            Name = name;
            LastName = lastName;
            Adress = adress;
            Phone = phone;
        }
    }
}

MVCHomework1/MVCHomework1/Models/Enum/PizzaType.cs
namespace MVCHomework1.Models.Enum
{
    public enum PizzaType
    {
        Margherita,
        Marinara,
        Capricciosa,
        QuattroStagioni,
        Diavola
    }
}

MVCHomework1/MVCHomework1/Models/ErrorViewModel.cs
namespace MVCHomework1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCHomework1/MVCHomework1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCHomework1.Models;
using System.Diagnostics;

namespace MVCHomework1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCHomework1/MVCHomework1/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using MVCHomework1.Models.Database;
using MVCHomework1.Models.Domain;

namespace MVCHomework1.Controllers
{
    [Route("pizza")]
    public class PizzaController : Controller
    {
        [Route("ListOrders")]
        public IActionResult Index()
        {
            List<Order> orders = PizzaDatabase.ORDERS;
            return View(orders);
        }

        [Route("details")]
        public IActionResult Details(int id)
        {
            Pizza pizza = PizzaDatabase.LIST_PIZZA.FirstOrDefault(x => x.Id == id);

            if (pizza is null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(pizza);
        }

        [Route("jsonData")]
        public IActionResult JsonData()
        {
            List<User> users = PizzaDatabase.USERS;
            return Json(users);
        }

        [Route("goHome")]
        public IActionResult GoHome()
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

MVCHomework1/MVCHomework1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCHomework1/MVCHomework1/Views/Pizza/Details.cshtml
@model MVCHomework1.Models.Domain.Pizza

@*
	For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	<h1>Pizza by ID</h1>

	<h4>Pizza: Id:@Model.Id Name:@Model.Name Price:@Model.Price</h4>
}

MVCHomework1/MVCHomework1/Views/Pizza/Index.cshtml
@using MVCHomework1.Models.Domain
@model List<MVCHomework1.Models.Domain.Order>
@*

	For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	<h1>List of Orders</h1>

	<ul>
		@foreach (Order order in @Model)
		{
			<li>
				<h5>Order Id:@order.Id   Price:@order.Price$  IsDelivered:@order.IsDelivered  User Id:@order.UserId   Pizza Id:@order.PizzaId </h5>
			</li>
		}
	</ul>
}

MVCHomework1/MVCHomework1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCHomework1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCHomework1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCHomework1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="GoHome">Home</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="JsonData">Json Data</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCHomework1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>